const food = [
  "Phở",
  "Bánh mì",
  "Cơm gà",
  "Bún chả",
  "Bánh xèo",
  "Hủ tiếu",
  "Bún riêu",
  "Bánh cuốn",
  "Bún bò Huế",
  "Cơm tấm",
  "Bánh mì xúc xích",
  "Bánh canh",
  "Bún ốc",
  "Bánh tráng trộn",
  "Cháo lòng",
  "Bún mắm",
  "Bánh tráng cuốn thịt heo",
  "Bánh bèo",
  "Bánh ướt",
  "Bánh tráng nướng",
  "Cháo cá",
  "Bánh đúc",
  "Gỏi cuốn",
  "Bún mọc",
  "Bánh tráng trộn",
  "Bánh bột lọc",
  "Nem chua",
  "Bánh canh cua",
  "Bánh mì pate",
  "Bún bò Nam Bộ",
  "Bánh mì chảo",
  "Chả giò",
  "Bánh mì nướng",
  "Cháo gà",
  "Bánh mì que",
  "Bún măng vịt",
  "Bánh xèo mực",
  "Ốc len xào dừa",
  "Bún đậu mắm tôm",
  "Bánh canh bột gạo",
  "Bánh bột lọc trần",
  "Bánh đa cua",
  "Bún bò Khánh Hòa",
  "Bánh tráng nướng trứng",
  "Bánh mì chảo bơ tỏi",
  "Bún mắm thịt quay",
  "Bánh đúc nóng",
  "Bún chả cá",
];
module.exports = food;
